name: Generate Documentation

# Trigger the workflow on push events for the master branch
on:  
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out repository
      - uses: actions/checkout@v2

      # Set up Python build environment and install pdoc3
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: ".github/workflows/requirements.txt"
      
      # Generate documentation for each package
      - run: pdoc --html -o docs -f voxelfuse
      - run: pdoc --html -o docs -f voxelfuse_examples

      # Create a pull request for updated documentation
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update documentation
          branch: documentation-updates
          delete-branch: true
          title: 'Update documentation'
          body: |
            Generate updated package documentation
            - Documentation generated using [pdoc][1]
            - Pull request auto-generated by [create-pull-request][2]

            [1]: https://pdoc3.github.io/pdoc/
            [2]: https://github.com/peter-evans/create-pull-request
          labels: documentation
          
